$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

$out = Join-Path $root "artifacts"
if (Test-Path $out) { Remove-Item $out -Recurse -Force }
New-Item -ItemType Directory -Path $out | Out-Null

# Portable build
$publishDir = Join-Path $out "portable"
dotnet publish .\src\VoiSER.Windows.App\VoiSER.Windows.App.csproj -c Release -r win-x64 --self-contained false -o $publishDir
Compress-Archive -Path "$publishDir\*" -DestinationPath (Join-Path $out "VoiSER-Windows-portable.zip")

# MSIX package placeholder path (depends on Windows SDK/MSIX tooling on runner)
Write-Host "MSIX build should be generated by CI release workflow using MSBuild packaging switches."
